/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f1xx.h"
#include "gpio.h"
#include "aht10.h"
#include "i2c.h"

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

    gpio_init(gpiob);
    afio_init();

    setup_pin(gpiob, P6, OUT_50MHZ, CNF_3);
    setup_pin(gpiob, P7, OUT_50MHZ, CNF_3);
    
    //ajeitar depois
    i2c_init(I2C_1, I2C_FREQ_2MHZ);
    i2c_int_enable(BUFFER_INT);
    i2c_int_enable(EVENT_INT);

    
	for(;;);
}
